spring.application.name=spring-data-jpa-partie8

# steep 1: config database
spring.datasource.url=jdbc:mysql://localhost:3306/demo-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# steep 2: config JPA/ Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# steep 3: port
sever.port=9090