spring.application.name=lombok-tutorial

# config database
spring.datasource.url=jdbc:h2:file:./data/lombok-3ia-community
spring.datasource.username=sa
spring.datasource.password=

# config JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# config H2
spring.h2.console.enabled=true
spring.h2.console.path=/lombok-3ia-console

# port
server.port=9090