# name of application
spring.application.name=crudProject

# config database
spring.datasource.url=jdbc:mysql://localhost:3306/spring-tutorial-mff
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090