
# Application Name
spring.application.name=couch-service-demo1

# Config DataBase
spring.datasource.url=jdbc:mysql://localhost:3306/couch-service-demo1
spring.datasource.username=root
spring.datasource.password=

# Config JPA/ Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true